<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Collab</name>
   <tag></tag>
   <elementGuidId>9b1823b5-1596-4fea-8c8e-f1641d0aec80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Collab > h4.sc-gFqAkR.lssH > a.sc-dsAker.eLPtcM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Collab']/h4/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Collab&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>41c7b52e-59f0-4519-b79e-c1aa67c737ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-dsAker eLPtcM</value>
      <webElementGuid>e1b983ec-83dc-4198-8e37-b443c3dd68eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collab</value>
      <webElementGuid>6e1f4d24-5bbc-45a2-ac56-36a5d02b7f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Collab</value>
      <webElementGuid>33630933-ef91-402c-97ad-61e34a72e31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Collab&quot;)/h4[@class=&quot;sc-gFqAkR lssH&quot;]/a[@class=&quot;sc-dsAker eLPtcM&quot;]</value>
      <webElementGuid>2d748a3b-ddfc-413d-a854-0e152bfae6a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Collab']/h4/a</value>
      <webElementGuid>8662ec20-c2cb-42f3-9871-aa05ee1a1c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Collab')]</value>
      <webElementGuid>1e27ac85-0724-4a17-b573-ce13a78a978b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>1527416a-82c9-4081-8968-eed17c15333f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketplace'])[1]/preceding::a[1]</value>
      <webElementGuid>a2cee156-dc0c-4aef-a3b5-4064cfaf97e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet'])[1]/preceding::a[2]</value>
      <webElementGuid>55a4deb6-e683-4266-bef8-a93759701312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Collab']/parent::*</value>
      <webElementGuid>a51c31ee-f72a-4632-ba55-b5b40b9ffd52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/collab')]</value>
      <webElementGuid>7a91fa8e-3235-4353-a359-18b245425ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h4/a</value>
      <webElementGuid>e9b87af5-92ac-4032-9a16-e18ea8ab20c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collab' and (text() = 'Collab' or . = 'Collab')]</value>
      <webElementGuid>b6d3c919-3a02-404e-889d-c66bf3317526</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
