<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Wallet</name>
   <tag></tag>
   <elementGuidId>c5232a97-08d5-48d3-b25f-16749a099f1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Wallet > h4.sc-gFqAkR.lssH > a.sc-dsAker.eLPtcM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Wallet']/h4/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Wallet&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d0800c5-5ef0-4e0f-a87e-48ddbf4c73f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-dsAker eLPtcM</value>
      <webElementGuid>277a8a37-a199-4f85-b31a-0d9de1b55835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wallet</value>
      <webElementGuid>25e03fd9-c965-4450-b6a3-9b5ace8e7423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wallet</value>
      <webElementGuid>ab1ee2a1-0c98-40c6-a0f4-7076fa51a971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Wallet&quot;)/h4[@class=&quot;sc-gFqAkR lssH&quot;]/a[@class=&quot;sc-dsAker eLPtcM&quot;]</value>
      <webElementGuid>39eeee1b-fd9d-430a-b167-cf52b4a05fa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wallet']/h4/a</value>
      <webElementGuid>b1e02ce4-d757-4de1-a7f7-1ecf013624c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Wallet')]</value>
      <webElementGuid>75b5acab-a67e-4469-ba29-c551de8ab5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketplace'])[1]/following::a[1]</value>
      <webElementGuid>9be86021-9920-46ab-acb1-9fc98aa6a5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collab'])[1]/following::a[2]</value>
      <webElementGuid>57fd413a-4e4b-4a0a-bbb6-d31c27193c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dark Mode'])[1]/preceding::a[3]</value>
      <webElementGuid>425e2c4e-1849-4205-b65c-c67e467d931e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wallet']/parent::*</value>
      <webElementGuid>c8e5db90-9d88-4e9f-b4c1-3c90f6bb0285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wallet')]</value>
      <webElementGuid>aef3e990-f8cb-4fb9-8cb9-3a601987491c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/h4/a</value>
      <webElementGuid>8d8c67e2-d244-4877-894e-045745e17b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wallet' and (text() = 'Wallet' or . = 'Wallet')]</value>
      <webElementGuid>d3116925-b78b-4445-9f76-2fc09b50fdff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
