<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Piggy Bank Balance</name>
   <tag></tag>
   <elementGuidId>82ecf3dc-9a32-424c-9e94-61340f501427</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.sc-eldPxv.cnaVXI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@type='h2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Piggy Bank Balance&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>e59e314f-aa37-48ce-aa96-6bb69bbedb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-eldPxv cnaVXI</value>
      <webElementGuid>a085657d-15c3-437d-82a8-1ddc1b085b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>a645015a-15e0-494a-95b2-a997209bf7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Piggy Bank Balance</value>
      <webElementGuid>6e490948-84f3-42ff-8707-ae66f7a524e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-gjYfiE cfzmpS&quot;]/main[@class=&quot;sc-hQQMGV bRntZB&quot;]/div[@class=&quot;sc-jaOLEC dCWMzC&quot;]/div[@class=&quot;sc-kqGoIF fHNFyl&quot;]/div[@class=&quot;sc-dxcDKg jKNfjV&quot;]/div[@class=&quot;sc-puSWb ezpHaY&quot;]/h2[@class=&quot;sc-eldPxv cnaVXI&quot;]</value>
      <webElementGuid>fdf468ef-f1bd-4040-bb54-385d7d631136</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@type='h2']</value>
      <webElementGuid>e4d61c33-c48d-4f51-9ca6-4a8cd229d4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div/div/h2</value>
      <webElementGuid>8d83ecbd-24bb-4e80-af7a-c69fd49f379c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dark Mode'])[1]/following::h2[1]</value>
      <webElementGuid>4facd9fe-20ca-4c43-a08f-49968513728e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet'])[1]/following::h2[1]</value>
      <webElementGuid>1988f9d1-8f66-4315-8a86-13ef2973a7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0'])[1]/preceding::h2[1]</value>
      <webElementGuid>a4586d53-d251-440f-ad81-00c9ff2744be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to Spin'])[1]/preceding::h2[1]</value>
      <webElementGuid>fd553515-237e-44bd-8469-88c3999429e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Piggy Bank Balance']/parent::*</value>
      <webElementGuid>8e1434c4-cc27-4f69-99f3-72762bc1300f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>301781d5-f8b3-4f64-967b-b6ef7c2c85e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@type = 'h2' and (text() = 'Piggy Bank Balance' or . = 'Piggy Bank Balance')]</value>
      <webElementGuid>1fbde15b-47f8-4235-baa9-fcdde2a51a74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
