<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Zeyad Alasad</name>
   <tag></tag>
   <elementGuidId>48e6c6f7-c838-4d27-8190-3d9fbeab4b33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.sc-jXbUNg.kQEzfi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=main >> internal:text=&quot;Zeyad Alasad&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>eab553ad-7353-4441-bdcd-bd238733ca00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-jXbUNg kQEzfi</value>
      <webElementGuid>5dd6f596-36b0-44fc-ae5b-5051ed3aac0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>496de163-cdef-475c-9071-5c5f09560e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zeyad Alasad</value>
      <webElementGuid>adeeb5ff-ca29-4979-8c35-4253c0f4a566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-gjYfiE cfzmpS&quot;]/main[@class=&quot;sc-hQQMGV bRntZB&quot;]/div[@class=&quot;sc-iVAfcr iTMIJS&quot;]/div[@class=&quot;sc-bxjOoZ jckLIQ&quot;]/div[@class=&quot;sc-lizKOf kwiyCx&quot;]/div[@class=&quot;sc-dWZqqJ dykyTd&quot;]/p[@class=&quot;sc-jXbUNg kQEzfi&quot;]</value>
      <webElementGuid>472469d2-fcf8-4080-825f-e506b5e903d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div/div/p</value>
      <webElementGuid>defa892b-36e6-49d7-b8a5-48f893d6a205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dark Mode'])[1]/following::p[3]</value>
      <webElementGuid>f6b891cf-1f8a-4e2b-b987-6daa779ab075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet'])[1]/following::p[7]</value>
      <webElementGuid>40a46bac-31e9-47dc-961f-60f19aba9a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Zeyad Alasad']/parent::*</value>
      <webElementGuid>479ed198-6073-4a02-ab2d-b937536c2d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div/p</value>
      <webElementGuid>09ce4fcd-494e-45ae-857c-26f1dc998cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Zeyad Alasad' or . = 'Zeyad Alasad')]</value>
      <webElementGuid>c7bf29d2-8c3c-4ca2-8b0b-e2c7933e0d09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
